/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as src from "./src";
export type { src };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Pausable } from "./@openzeppelin/contracts/security/Pausable";
export { Pausable__factory } from "./factories/@openzeppelin/contracts/security/Pausable__factory";
export type { Ballot } from "./src/contracts/Ballot";
export { Ballot__factory } from "./factories/src/contracts/Ballot__factory";
export type { VoterRegistry } from "./src/contracts/VoterRegistry";
export { VoterRegistry__factory } from "./factories/src/contracts/VoterRegistry__factory";
